{
 "title": "Nexus Infrastructure",
 "description": "Overview for Nexus",
 "tags": [ "maintenance" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jvm_vm_uptime", "legendFormat": "used" }
   ]
  },
  {
   "title": "Heap Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jvm_memory_heap_usage", "legendFormat": "used" }
   ]
  },
  {
   "title": "FileDescriptor Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jvm_fd_usage", "legendFormat": "used" }
   ]
  },
  { "title": "Nexus Component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "SecurityComponent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_rapture_internal_security_SecurityComponent_getPermissions_timer{quantile=\"0.5\"}",
     "legendFormat": "getPermissions - p50"
    },
    {
     "expr": "org_sonatype_nexus_rapture_internal_security_SecurityComponent_getPermissions_timer{quantile=\"0.99\"}",
     "legendFormat": "getPermissions - p99"
    },
    {
     "expr": "org_sonatype_nexus_rapture_internal_security_SecurityComponent_getUser_timer{quantile=\"0.5\"}",
     "legendFormat": "getUser - p50"
    },
    {
     "expr": "org_sonatype_nexus_rapture_internal_security_SecurityComponent_getUser_timer{quantile=\"0.99\"}",
     "legendFormat": "getUser - p99"
    }
   ]
  },
  {
   "title": "RepositoryComponent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_getBrowseableFormats_timer{quantile=\"0.5\"}",
     "legendFormat": "getBrowseableFormats - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_getBrowseableFormats_timer{quantile=\"0.99\"}",
     "legendFormat": "getBrowseableFormats - p99"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_readReferences_timer{quantile=\"0.5\"}",
     "legendFormat": "readReferences - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_readReferences_timer{quantile=\"0.99\"}",
     "legendFormat": "readReferences - p99"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_read_timer{quantile=\"0.5\"}",
     "legendFormat": "read - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_read_timer{quantile=\"0.99\"}",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "SearchComponent Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_coreui_SearchComponent_read_timer{quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_SearchComponent_read_timer{quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "FileBlobStore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_copy_timer{quantile=\"0.5\"}",
     "legendFormat": "copy - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_copy_timer{quantile=\"0.99\"}",
     "legendFormat": "copy - p99"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_deleteHard_timer{quantile=\"0.5\"}",
     "legendFormat": "deleteHard - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_deleteHard_timer{quantile=\"0.99\"}",
     "legendFormat": "deleteHard - p99"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_get_timer{quantile=\"0.5\"}",
     "legendFormat": "get - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_get_timer{quantile=\"0.5\"}",
     "legendFormat": "get - p99"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_delete_timer{quantile=\"0.5\"}",
     "legendFormat": "delete - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_delete_timer{quantile=\"0.99\"}",
     "legendFormat": "delete - p99"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_create_timer{quantile=\"0.5\"}",
     "legendFormat": "create - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_create_timer{quantile=\"0.99\"}",
     "legendFormat": "create - p99"
    }
   ]
  },
  {
   "title": "UserComponent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_coreui_UserComponent_readSources_timer{quantile=\"0.5\"}",
     "legendFormat": "readSources - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_UserComponent_readSources_timer{quantile=\"0.99\"}",
     "legendFormat": "readSources - p99"
    },
    {
     "expr": "org_sonatype_nexus_coreui_UserComponent_read_timer{quantile=\"0.5\"}",
     "legendFormat": "read - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_UserComponent_read_timer{quantile=\"0.99\"}",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "Component Exceptions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_sonatype_nexus_coreui_BlobStoreComponent_readGroups_exceptions_total[5m])",
     "legendFormat": "BlobStoreComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_blobstore_s3_internal_ui_S3Component_signertypes_exceptions_total[5m])",
     "legendFormat": "S3Component"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_TaskComponent_update_exceptions_total[5m])",
     "legendFormat": "TaskComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_rapture_internal_state_StateComponent_getState_exceptions_total[5m])",
     "legendFormat": "StateComponent"
    },
    {
     "expr": "rate(com_sonatype_nexus_migration_ui_AssistantComponent_cancel_exceptions_total[5m])",
     "legendFormat": "AssistantComponent-Cancel"
    },
    {
     "expr": "rate(com_sonatype_nexus_migration_ui_AssistantComponent_abort_exceptions_total[5m])",
     "legendFormat": "AssistantComponent-Abort"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_FreezeComponent_update_exceptions_total[5m])",
     "legendFormat": "FreezeComponent-Update"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_FreezeComponent_read_exceptions_total[5m])",
     "legendFormat": "FreezeComponent-Read"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_SelectorComponent_readReferences_exceptions_total[5m])",
     "legendFormat": "SelectorComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_RepositoryComponent_rebuildIndex_exceptions_total[5m])",
     "legendFormat": "RepositoryComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_verifyLogin_exceptions_total[5m])",
     "legendFormat": "LdapServerComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_BrowseComponent_read_exceptions_total[5m])",
     "legendFormat": "BrowseComponent"
    },
    {
     "expr": "rate(com_sonatype_nexus_clm_internal_ui_ClmComponent_readApplications_exceptions_total[5m])",
     "legendFormat": "ClmComponent-Read"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_internal_capability_CapabilityComponent_remove_exceptions_total[5m])",
     "legendFormat": "CapabilityComponent-Remove"
    },
    {
     "expr": "rate(com_sonatype_nexus_ssl_plugin_internal_ui_CertificateComponent_details_exceptions_total[5m])",
     "legendFormat": "CertificateComponent-Details"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_SearchComponent_read_exceptions_total[5m])",
     "legendFormat": "SearchComponent-Read"
    },
    {
     "expr": "rate(org_sonatype_nexus_rapture_internal_security_SecurityComponent_authenticate_exceptions_total[5m])",
     "legendFormat": "SecurityComponent-Authenticate"
    },
    {
     "expr": "rate(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_changeOrder_exceptions_total[5m])",
     "legendFormat": "LdapServerComponent-ChangeOrder"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_RepositoryComponent_remove_exceptions_total[5m])",
     "legendFormat": "RepositoryComponent-Remove"
    },
    {
     "expr": "rate(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_readReferences_exceptions_total[5m])",
     "legendFormat": "LdapServerComponent-Read"
    }
   ]
  },
  { "title": "Jetty WebAppContext", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Jetty Responses Code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_1xx_responses_total[1m])",
     "legendFormat": "1xx"
    },
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_2xx_responses_total[1m])",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_5xx_responses_total[1m])",
     "legendFormat": "5xx"
    },
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_4xx_responses_total[1m])",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_3xx_responses_total[1m])",
     "legendFormat": "3xx"
    }
   ]
  },
  {
   "title": "Jetty Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_eclipse_jetty_webapp_WebAppContext_requests{quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "org_eclipse_jetty_webapp_WebAppContext_requests{quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_garbage_collectors_PS_MarkSweep_count[1m])",
     "legendFormat": "major GC(marksweep)"
    },
    {
     "expr": "rate(jvm_garbage_collectors_PS_Scavenge_count[1m])",
     "legendFormat": "minor GC(scavenge)"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_heap_max", "legendFormat": "max" },
    { "expr": "jvm_memory_heap_used", "legendFormat": "used" },
    { "expr": "jvm_memory_heap_committed", "legendFormat": "committed" }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_non_heap_max", "legendFormat": "max" },
    { "expr": "jvm_memory_non_heap_used", "legendFormat": "used" },
    { "expr": "jvm_memory_non_heap_committed", "legendFormat": "committed" }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_total_max", "legendFormat": "max" },
    { "expr": "jvm_memory_total_used", "legendFormat": "used" },
    { "expr": "jvm_memory_total_committed", "legendFormat": "committed" }
   ]
  },
  { "title": "JVM Memory Pools (Heap) ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "PS Eden Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_PS_Eden_Space_used",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_PS_Eden_Space_max",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_PS_Eden_Space_committed",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "PS Old Gen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_PS_Old_Gen_used",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_PS_Old_Gen_max",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_PS_Old_Gen_committed",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_PS_Survivor_Space_used",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_PS_Survivor_Space_max",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_PS_Survivor_Space_committed",
     "legendFormat": "committed"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Metaspace_used",
     "legendFormat": "used"
    },
    { "expr": "jvm_memory_pools_Metaspace_max", "legendFormat": "max" },
    {
     "expr": "jvm_memory_pools_Metaspace_committed",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Compressed_Class_Space_used",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_Compressed_Class_Space_max",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_Compressed_Class_Space_committed",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Code_Cache_used",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_Code_Cache_max",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_Code_Cache_committed",
     "legendFormat": "committed"
    }
   ]
  },
  { "title": "JVM Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_buffers_direct_count", "legendFormat": "count" }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_buffers_direct_used", "legendFormat": "used" },
    { "expr": "jvm_buffers_direct_capacity", "legendFormat": "capacity" }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_buffers_mapped_count", "legendFormat": "count" }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_buffers_mapped_used", "legendFormat": "used" },
    { "expr": "jvm_buffers_mapped_capacity", "legendFormat": "capacity" }
   ]
  },
  {
   "title": "Thread",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_thread_states_daemon_count", "legendFormat": "daemon" },
    {
     "expr": "jvm_thread_states_terminated_count",
     "legendFormat": "terminated"
    },
    { "expr": "jvm_thread_states_count", "legendFormat": "total" }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_thread_states_new_count", "legendFormat": "new" },
    {
     "expr": "jvm_thread_states_runnable_count",
     "legendFormat": "runnable"
    },
    {
     "expr": "jvm_thread_states_blocked_count",
     "legendFormat": "blocked"
    },
    {
     "expr": "jvm_thread_states_deadlock_count",
     "legendFormat": "deadlock"
    },
    {
     "expr": "jvm_thread_states_timed_waiting_count",
     "legendFormat": "timed_waiting"
    },
    {
     "expr": "jvm_thread_states_waiting_count",
     "legendFormat": "waiting"
    }
   ]
  }
 ]
}